using UnityEngine;
using System.Collections;

public class LightmapSwap : MonoBehaviour
{
    public void Swap()
    {
        // Swap the active and inactive lightmaps
        // NOTE: Will only work if both sets of lightmaps are the same size!
        LightmapData[] temp = LightmapSettings.lightmaps;
        LightmapSettings.lightmaps = inactiveMaps;
        inactiveMaps = temp;
    }

    // The actual lightmap files generated by Beast
    [SerializeField] private Texture2D[] textures;

    private LightmapData[] inactiveMaps;

    private void Awake()
    {
        // Generate the final array of LightmapData using the baked textures
        inactiveMaps = new LightmapData[textures.Length];
        for (int i = 0; i < inactiveMaps.Length; i++) {
            inactiveMaps[i] = new LightmapData();
            inactiveMaps[i].lightmapFar = textures[i];
            inactiveMaps[i].lightmapNear = null;
        }
    }
}